development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url:     postgres://jrdxmasonlnian:0ee2daa270b636becc9aae9cfb056e5d8bdbeafd36ca6ea263ece45ff1337181@ec2-54-243-47-252.compute-1.amazonaws.com:5432/d381hcuj6114ev
  channel_prefix: buxteben_production
